# Generated by Django 5.1.6 on 2025-02-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificação', models.CharField(max_length=50)),
                ('codigo_insumo', models.IntegerField()),
                ('descrição_insumo', models.TextField()),
                ('unidade', models.CharField(max_length=50)),
                ('origem_preço', models.CharField(max_length=50)),
            ],
        ),
    ]
