# Generated by Django 5.1.6 on 2025-02-09 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_uploadedfile_origem_preço'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedFile',
            new_name='insumos',
        ),
    ]
