# Generated by Django 5.1.6 on 2025-02-09 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_rename_uploadedfile_insumos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumos',
            name='uploaded_at',
        ),
    ]
